### ISSUE TITLE
How to transform text nodes?

### ISSUE THREAD

**Issue by Sanva** [rhysd/rehype-react#17]
Hi!

I'm currently testing Gatsby with `gatsby-transformer-remark`, which uses `remark` under the hood as far as I known. I'm trying `rehype-react` and it works really well, but I have a problem: How to transform text nodes?

I mean, for example having this AST:

```json
{
        "type": "root",
        "children": [
          {
            "type": "element",
            "tagName": "p",
            "properties": {},
            "children": [
              {
                "type": "text",
                "value": "Do Pandas eat bananas? Check out this short video that\nshows that yes! pandas do\nseem to really enjoy bananas!"
              }
            ]
          },
          {
            "type": "text",
            "value": "\n"
          },
        ],
        "data": {
          "quirksMode": false
        }
      }
```

I can easily transform the `p` tag to another thing, for example with

```javascript
const renderAst = new rehypeReact({
  createElement: React.createElement,
  components: {
    p: ({ children }) => <Text>{children}</Text>,
    text: ({ children }) => <Text>{children}</Text>,
  },
}).Compiler
```

But `text` nodes are ignored — maybe because there aren't of type `element`?

Do you know if it is possible to replace them just like normal elements?

**Comment by wooorm** [comment]
Hey @Sanva! Whether this should be added or not, I don’t know, but I’m also wondering if wouldn’t add a big performance bottleneck: it’s a lot of components.

Could you expand more on the background of what you’re trying to do, the why?

**Comment by Sanva** [comment]
Hi!

> [...] I’m also wondering if wouldn’t add a big performance bottleneck: it’s a lot of components [...]

No problem, it was only some tests on a side project — I was trying to make a prototype building React Native components out of Markdown, and I've found it easy using `rehype-react`, but it looks like the AST maintains the new lines present in the source code, and React `Text` elements renders them, which creates problems.

I think I'll go and use `pandoc` for this, so I'm closing this issue, the question was only because I've thought maybe there was some option to treat them like the other elements.
