### ISSUE TITLE
Attribute conversion

### ISSUE THREAD

**Issue by davidtheclark** [rhysd/rehype-react#5]
I don't think all attributes are being converted from their HTML names to their React-compatible equivalents.

I am not sure if this is the right place to do that or not (is there a better place for this in the unified/rehype world?). https://github.com/noraesae/react-attr-converter could be used to handle the logic.

**Comment by wooorm** [comment]
👋

Could you share more of what’s going wrong? What properties aren’t converted correctly? What’s your set-up

**Comment by davidtheclark** [comment]
I'm using `rehype-parse` and `rehype-react` with the goal of converting SVGs to React elements (and ultimately JSX). 

Here's my processor:

```js
unified()
  .use(rehypeParse, { fragment: true })
  .use(rehypeReact, {
    createElement: React.createElement
  });
```

Some examples of incorrect attributes that I'm seeing:
- `view-box` should be `viewBox`
- `clip-path` should be `clipPath`
- `font-family` should be `fontFamily`
- `font-size` should be `fontSize`

**Comment by davidtheclark** [comment]
I filed this generic issue instead of targeting specific attributes because I did not manage to find any code that would effectively transform all these attributes to their React equivalents — so I thought maybe it had been overlooked. (Or maybe I just couldn't find it.)

**Comment by wooorm** [comment]
Oh I get that! unified is a big system, and there’s a lot of places to ask for Qs, no problem!

So, unfortunately I haven’t figured out how to do SVG properly in rehype. 😬 rehype is for HTML, and I’m not entirely sure how to handle SVG in HTML. We probably need something like [`property-information`](https://github.com/wooorm/property-information) for SVG... I’d love to get feedback on that, or how to handle XML namespaces (SVG is one) in [HAST](https://github.com/syntax-tree/hast).

We talked about it a bit in https://github.com/syntax-tree/hast/issues/6, but still, not sure how to handle it properly...

**Comment by davidtheclark** [comment]
🤔  so it sounds like this issue is not about attribute conversion but about SVG handling — in which case it's not really suited to this particular library. I'll close the issue 👍

**Comment by wooorm** [comment]
I’d love to add it somewhere in the future, but unfortunately not yet sure how!
